
server {
    listen 80;
    location /vehicles { proxy_pass http://api:8000; }
    location /customers { proxy_pass http://api:8000; }
    location /docs { proxy_pass http://api:8000; }
    location /openapi.json { proxy_pass http://api:8000; }
    location /minio/vehicles/ { proxy_pass http://minio:9000/vehicles/; }
}
